[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# For dependencies
remappings = [
]
